<?xml version="1.0" encoding="UTF-8" ?>

<!--
    Document   : mainHtmlGen.xsl
    Created on : 16 January 2003, 14:08
    Author     : jejking
    Description:
        Turns our no-layout specific html.xml source into pages
        ready for deployment.
        This should ensure that we can tinker with layout and structure of the web
        pages in one place - the xsl stylesheet with further visual tinkering in the CSS.
        In this way we decouple information and (minimal) view logic from visuals.
        Conceivably, by piping the same source through a different set of stylesheets,
        we could render it nicely for other display devices. But that's all in the future yet.
    $Header$
    Version: $Revision$
    
 * Copyright (C) 2003  John King
 *
 * This file is part of the authorsite.org bibliographic
 * application.
 *
 * This application is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
-->

<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    
    <xsl:output method="xml"
                indent="yes"
                doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN"
                doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"/>
    
    <xsl:include href="genericWebGen.xsl"/>
    
    <xsl:param name="base"/>
    <xsl:param name="today"/>
    <xsl:param name="htmlOnly"/>
    
    <xsl:template match="/">
        <html xml:lang="en">
            <head>
                <xsl:if test="$base">
                    <base href="{$base}"/>
                </xsl:if>
                <title><xsl:value-of select="/doc/ia/title"/></title>
                <link rel="stylesheet" href="css/main.css" type="text/css"/>
                <xsl:if test="$htmlOnly">
                    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
                    <xsl:copy-of select="/doc/ia/metatags/*"/>
                </xsl:if>
            </head>
            <xsl:comment>
                HTML generated by mainHtmlGen.xsl <xsl:value-of select="$today"/>
            </xsl:comment>
            <xsl:call-template name="buildMainBody"/>
                
        </html>
    </xsl:template>
</xsl:stylesheet> 
