INSERT INTO HUMAN (DTYPE, ID, VERSION, CREATEDAT, CREATEDBY, UPDATEDAT, UPDATEDBY, NAME, GIVENNAMES)
    VALUES( 'Individual', 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0, 'User', 'Super');

-- user root has password 'password'
INSERT INTO SYSTEMUSER (ID, VERSION, CREATEDAT, CREATEDBY, UPDATEDAT, UPDATEDBY, PASSWORD, ENABLED, USERNAME, INDIVIDUAL_ID)
    VALUES(0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, '2ae31c06cd0b3156be7767288aa401dcbd0ab7e032d4ec3f267f7c9960214609', 1, 'root', 0);

INSERT INTO SYSTEMUSER_AUTHORITIES(SYSTEMUSER_ID, ELEMENT) VALUES (0, 0);
INSERT INTO SYSTEMUSER_AUTHORITIES(SYSTEMUSER_ID, ELEMENT) VALUES (0, 1);
