create table Human 
(
    DTYPE varchar(31) not null, 
    id bigint generated by default as identity (start with 1) not null,
    version integer not null, 
    createdAt timestamp,
    updatedAt timestamp,
    name varchar(255),
    nameQualification varchar(255),
    place varchar(255),
    givenNames varchar(255),
    createdBy_id bigint not null,
    updatedBy_id bigint not null
);

alter table Human add constraint PK_HUMAN primary key (id);
alter table Human add constraint FK_HUMAN_CREATED_BY foreign key (createdBy_id) references Human(id);
alter table Human add constraint FK_HUMAN_UPDATED_BY foreign key (updatedBy_id) references Human(id);

create table SystemUser 
(
    id bigint generated by default as identity (start with 1) not null,
    version integer not null,
    createdAt timestamp, 
    updatedAt timestamp, 
    userName varchar(255) not null,
    enabled smallint not null,
    password varchar(255) not null,
    individual_id bigint not null,
    createdBy_id bigint not null,
    updatedBy_id bigint not null
);

alter table SystemUser add constraint PK_SYSTEM_USER primary key (id);
alter table SystemUser add constraint UQ_SU_INDIVIDUAL unique(individual_id);
alter table SystemUser add constraint FK_SU_CREATED_BY foreign key (createdBy_id) references Human(id);
alter table SystemUser add constraint FK_SU_UPDATED_BY foreign key (updatedBy_id) references Human(id);
alter table SystemUser add constraint FK_SU_HUMAN foreign key (individual_id) references Human(id);

create table SystemUser_Authorities (
    SystemUser_id bigint not null,
    element integer not null
);

alter table SystemUser_Authorities add constraint FK_SUA_SU foreign key (SystemUser_id) references SystemUser(id);

create table acl_sid
(
    id bigint generated by default as identity (start with 1) not null,
    principal smallint not null,
    sid varchar(100) not null
);
alter table acl_sid add constraint PK_ACL_SID primary key (id); 
alter table acl_sid add constraint UQ_ACL_SID unique(sid, principal);

create table acl_class
(
    id bigint generated by default as identity (start with 1) not null,
    class varchar(255) not null
    
);
alter table acl_class add constraint PK_ACL_CLASS primary key (id);
alter table acl_class add constraint UQ_ACL_CLASS unique(class);


create table acl_object_identity
(
    id bigint generated by default as identity (start with 1) not null,
    object_id_class bigint not null,
    object_id_identity bigint not null,
    parent_object bigint,
    owner_sid bigint,
    entries_inheriting smallint not null
);
alter table acl_object_identity add constraint PK_ACL_OBJECT_IDENTITY primary key(id);
alter table acl_object_identity add constraint UQ_ACL_OBJECT_IDENTITY unique(object_id_class, object_id_identity);
alter table acl_object_identity add constraint FK_AOI_PARENT_OBJECT foreign key (parent_object) references acl_object_identity(id);
alter table acl_object_identity add constraint FK_AOI_OBJECT_ID_CLASS foreign key (object_id_class) references acl_class(id);
alter table acl_object_identity add constraint FK_AOI_OWNER_SID foreign key (owner_id) references acl_sid(id);


create table acl_entry
(
    id bigint generated by default as identity (start with 1) not null,
    acl_object_identity bigint not null,
    ace_order integer not null,
    sid bigint not null,
    mask integer not null,
    granting smallint not null,
    audit_success smallint not null,
    audit_failure smallint not null
);
alter table acl_entry add constraint PK_ACL_ENTRY primary key (id);
alter table acl_entry add constraint UQ_ACL_ENTRY unique (acl_object_identity, ace_order);
alter table acl_entry add constraint FK_AE_ACL_OBJECT_IDENTITY foreign key (acl_object_identity) references acl_object_identity(id);
alter table acl_entry add constraint FK_AE_SID foreign key (sid) references acl_sid(id);
