/**
 * This file is part of the authorsite application.
 *
 * The authorsite application is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * The authorsite application is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the authorsite application; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 * 
 */
package org.authorsite.security;

import org.acegisecurity.GrantedAuthority;

/**
 * Implementation of Acegi's {@link GrantedAuthority} wrapping
 * Authorsite internal {@link Authority}.
 * 
 * @author jejking
 */
public class AuthorsiteGrantedAuthority implements GrantedAuthority {

    /**
     * Generated by Eclipse.
     */
    private static final long serialVersionUID = -5922606889105733497L;

    private final Authority authority;

    /**
     * Creates a new instance of AuthorsiteGrantedAuthority
     *  
     * @param authority 
     */
    public AuthorsiteGrantedAuthority(Authority authority) {
	this.authority = authority;
    }

    public String getAuthority() {
	return "ROLE_" + this.authority.getRoleName().toUpperCase();
    }

    @Override
    public String toString() {
	return this.getAuthority();
    }

}
