/**
 * This file is part of the authorsite application.
 *
 * The authorsite application is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * The authorsite application is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the authorsite application; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 * 
 */
package org.authorsite.domain.bib;

import org.apache.commons.lang.builder.CompareToBuilder;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * Class describing a journal as a whole series of regular
 * publications. It does not describe individual issues or volumes
 * or a journal.
 * 
 * <p>It may also be used to describe newspapers.</p>. 
 * 
 * @author jejking
 */
public class Journal extends AbstractWork implements Comparable<Journal> {

    /**
     * Generated by Eclipse.
     */
    private static final long serialVersionUID = 6400922520162391883L;

    /**
     * Default constructor.
     */
    public Journal() {
	super();
    }

    @Override
    public boolean equals(Object obj) {
	if (obj == null) {
	    return false;
	}
	if (obj == this) {
	    return true;
	}
	if (obj instanceof Journal) {
	    Journal rhs = (Journal) obj;
	    return new EqualsBuilder().append(this.getTitle(), rhs.getTitle()).isEquals();
	} else {
	    return false;
	}
    }

    @Override
    public int hashCode() {
	return new HashCodeBuilder().append(this.getTitle()).toHashCode();
    }

    public int compareTo(Journal journal) {
	return new CompareToBuilder().append(this.getTitle(), journal.getTitle()).toComparison();
    }

    @Override
    public String toString() {
	return this.getTitle();
    }

}
