/**
 * This file is part of the authorsite application.
 *
 * The authorsite application is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * The authorsite application is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the authorsite application; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 * 
 */
package org.authorsite.domain.email;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * Binary message part wraps raw binary content.
 * 
 * @author jejking
 *
 */
public class BinaryMessagePart extends AbstractMessagePart {

    /**
     * Generated by Eclipse. 
     */
    private static final long serialVersionUID = -5655907176256410164L;

    private byte[] content;

    /**
     * Default constructor.
     */
    public BinaryMessagePart() {
	super();
    }

    /**
     * Constructs object setting properties to the values
     * in the parameters.
     * 
     * @param mimeType
     * @param content
     */
    public BinaryMessagePart(String mimeType, byte[] content) {
	super.setMimeType(mimeType);
	this.setContent(content);
    }

    /**
     * @return content as raw byte array
     */
    public byte[] getContent() {
	return this.content;
    }

    /**
     * Set content.
     * 
     * @param content
     */
    public void setContent(byte[] content) {
	this.content = content;
    }

    @Override
    public int getSize() {
	if (this.content != null) {
	    return this.content.length;
	} else {
	    return 0;
	}
    }

    @Override
    public int hashCode() {
	return new HashCodeBuilder().append(super.hashCode()).append(this.mimeType).append(this.content).toHashCode();
    }

    @Override
    public boolean equals(Object obj) {
	if (this == obj)
	    return true;
	if (obj == null)
	    return false;
	if (getClass() != obj.getClass())
	    return false;
	final BinaryMessagePart other = (BinaryMessagePart) obj;
	return new EqualsBuilder().appendSuper(super.equals(obj)).append(this.mimeType, other.mimeType).append(
		this.content, other.content).isEquals();
    }

    @Override
    public String toString() {
	StringBuilder builder = new StringBuilder();
	builder.append("TextMessagePart:\n");
	builder.append("File Name: " + this.fileName + "\n");
	builder.append("Mime Type: " + this.mimeType + "\n");
	if (this.description != null) {
	    builder.append("Description: " + this.description + "\n");
	}
	if (this.disposition != null) {
	    builder.append("Disposition: " + this.disposition + "\n");
	}
	return builder.toString();
    }

}
