/**
 * This file is part of the authorsite application.
 *
 * The authorsite application is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * The authorsite application is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the authorsite application; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 * 
 */

package org.authorsite.domain.email;

import java.io.UnsupportedEncodingException;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * Textual message part, content is represented as a string.
 * 
 * @author jejking
 *
 */
public class TextMessagePart extends AbstractMessagePart {

    /**
     * Generated by Eclipse.
     */
    private static final long serialVersionUID = -1742031284961397967L;

    private String content;

    /**
     * Default constructor.
     */
    public TextMessagePart() {
	super();
    }

    /**
     * Constructs object, setting properties from parameters.
     * 
     * @param mimeType
     * @param content
     */
    public TextMessagePart(String mimeType, String content) {
	super.setMimeType(mimeType);
	this.content = content;
    }

    /**
     * @return content
     */
    public String getContent() {
	return this.content;
    }

    /**
     * Sets content.
     * 
     * @param content
     */
    public void setContent(String content) {
	this.content = content;
    }

    @Override
    public int getSize() {
	if (this.content != null) {
	    try {
		return this.content.getBytes("UTF-8").length;
	    } catch (UnsupportedEncodingException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
		return -1;
	    }
	} else {
	    return 0;
	}
    }

    @Override
    public int hashCode() {
	return new HashCodeBuilder().appendSuper(super.hashCode()).append(this.mimeType).append(this.content)
		.toHashCode();
    }

    @Override
    public boolean equals(Object obj) {
	if (this == obj)
	    return true;
	if (obj == null)
	    return false;
	if (getClass() != obj.getClass())
	    return false;
	final TextMessagePart other = (TextMessagePart) obj;
	return new EqualsBuilder().appendSuper(super.equals(obj)).append(this.mimeType, other.mimeType).append(
		this.content, other.content).isEquals();
    }

    @Override
    public String toString() {
	StringBuilder builder = new StringBuilder();
	builder.append("TextMessagePart:\n");
	builder.append("File Name: " + this.fileName + "\n");
	builder.append("Mime Type: " + this.mimeType + "\n");
	if (this.description != null) {
	    builder.append("Description: " + this.description + "\n");
	}
	if (this.disposition != null) {
	    builder.append("Disposition: " + this.disposition + "\n");
	}
	builder.append("Content:\n" + this.content + "\n");
	return builder.toString();
    }
}
